#!/usr/bin/env python
# coding: utf-8

# In[24]:


word =[ '4u',
 'loan',
 'claims you are a winner',
 'for instant access',
 'accept credit cards',
 'claims you registered with some kind of partner',
 'for just $ (some amt)',
 'act now! don’t hesitate!',
 'click',
 'below',
 'free access',
 'additional income',
 'click here link',
 'free cell phone',
 'addresses on cd',
 'click to remove',
 'free consultation',
 'all natural',
 'click to remove mailto',
 'free dvd',
 'amazing',
 'compare rates',
 'free grant money',
 'apply online',
 'compete for your business',
 'free hosting',
 'as seen on',
 'confidentially on all orders',
 'free installation',
 'auto email removal',
 'congratulations',
 'free investment',
 'avoid bankruptcy',
 'consolidate debt and credit',
 'free leads',
 'be amazed',
 'copy accurately',
 'free membership',
 'be your own boss',
 'copy dvds',
 'free money',
 'being a member',
 'credit bureaus',
 'free offer',
 'big bucks',
 'credit card offers',
 'free preview',
 'bill 1618',
 'cures baldness',
 'free priority mail',
 'billing address',
 'dear email',
 'free quote',
 'billion dollars',
 'dear friend',
 'free sample',
 'brand new pager',
 'dear somebody',
 'free trial',
 'bulk email',
 'different reply to',
 'free website',
 'buy direct',
 'dig up dirt on friends',
 'full refund',
 'buying judgments',
 'direct email',
 'get it now',
 'cable converter',
 'direct marketing',
 'get paid',
 'call free',
 'discusses search engine listings',
 'get started now',
 'call now',
 'do it today',
 'gift certificate',
 'calling creditors',
 'don’t delete',
 'great offer',
 'can’t live without',
 'drastically reduced',
 'guarantee',
 'cancel at any time',
 'earn per week',
 'have you been turned down?',
 'cannot be combined with any other offer',
 'easy terms',
 'hidden assets',
 'cash bonus',
 'eliminate bad credit',
 'home employment',
 'cashcashcash',
 'email harvest',
 'human growth hormone',
 'casino',
 'email marketing',
 'if only it were that easy',
 'cell phone cancer scam',
 'expect to earn',
 'in accordance with laws',
 'cents on the dollar',
 'fantastic deal',
 'increase sales',
 'check or money order',
 'fast viagra delivery',
 'increase traffic',
 'claims not to be selling anything',
 'financial freedom',
 'insurance',
 'claims to be in accordance with some spam law',
 'find out anything',
 'investment decision',
 'claims to be legal',
 'for free',
 "it's effective",
 'join millions of americans',
 'no questions asked',
 'reverses aging',
 'laser printer',
 'no selling',
 'risk free',
 'limited time only',
 'no strings attached',
 'round the world',
 'long distance phone offer',
 'not intended',
 's 1618',
 'lose weight spam',
 'off shore',
 'safeguard notice',
 'lower interest rates',
 'offer expires',
 'satisfaction guaranteed',
 'lower monthly payment',
 'offers coupon',
 'save $',
 'lowest price',
 'offers extra cash',
 'save big money',
 'luxury car',
 'offers free (often stolen) passwords',
 'save up to',
 'mail in order form',
 'once in lifetime',
 'score with babes',
 'marketing solutions',
 'one hundred percent free',
 'section 301',
 'mass email',
 'one hundred percent guaranteed',
 'see for yourself',
 'meet singles',
 'one time mailing',
 'sent in compliance',
 'member stuff',
 'online biz opportunity',
 'serious cash',
 'message contains disclaimer',
 'online pharmacy',
 'serious only',
 'mlm',
 'only $',
 'shopping spree',
 'money back',
 'opportunity',
 'sign up free today',
 'money making',
 'opt in',
 'social security number',
 'month trial offer',
 'order now',
 'special promotion',
 'more internet traffic',
 'order status',
 'stainless steel',
 'mortgage rates',
 'orders shipped by priority mail',
 'stock alert',
 'multi level marketing',
 'outstanding values',
 'stock disclaimer statement',
 'name brand',
 'pennies a day',
 'stock pick',
 'new customers only',
 'people just leave money laying around',
 'stop snoring',
 'new domain extensions',
 'please read',
 'strong buy',
 'nigerian',
 'potential earnings',
 'stuff on sale',
 'no age restrictions',
 'print form signature',
 'subject to credit',
 'no catch',
 'print out and fax',
 'supplies are limited',
 'no claim forms',
 'produced and sent out',
 'take action now',
 'no cost',
 'profits',
 'talks about hidden charges',
 'no credit check',
 'promise you …!',
 'talks about prizes',
 'no disappointment',
 'pure profit',
 'tells you it’s an ad',
 'no experience',
 'real thing',
 'terms and conditions',
 'no fees',
 'refinance home',
 'the best rates',
 'no gimmick',
 'removal instructions',
 'the following form',
 'no inventory',
 'remove in quotes',
 'they keep your money — no refund!',
 'no investment',
 'remove subject',
 'they’re just giving it away',
 'no medical exams',
 'removes wrinkles',
 'this isn’t junk',
 'no middleman',
 'reply remove subject',
 'this isn’t spam',
 'no obligation',
 'requires initial investment',
 'university diplomas',
 'no purchase necessary',
 'reserves the right',
 'unlimited',
 'unsecured credit/debt',
 'we honor all',
 'will not believe your eyes',
 'urgent',
 'weekend getaway',
 'winner',
 'us dollars',
 'what are you waiting for?',
 'winning',
 'vacation offers',
 'while supplies last',
 'work at home',
 'viagra and other drugs',
 'while you sleep',
 'you have been selected',
 'wants credit card',
 'who really wins?',
 'your income',
 'we hate spam',
 'why pay more?',
 'buy direct buying judgments',
 'clearance',
 'order order status',
 'orders shipped by',
 'shopper personal dig up dirt on friends ',
 'meet singles ',
 'score with babes employment ',
 'additional income',
 'be your own boss',
 'compete for your business double your',
 'earn $',
 'earn extra cash earn per week ',
 'expect to earn ',
 'extra income home based',
 'home employment',
 'homebased business income from home',
 'make $',
 'make money money making',
 'online biz opportunity',
 'online degree opportunity ',
 'potential earnings ',
 'university diplomas while you sleep ',
 'work at home ',
 'work from home financial - general $$$',
 'affordable',
 'bargain beneficiary',
 'best price',
 'big bucks',
 'cash',
 'cash bonus ',
 'cashcashcash cents on the dollar ',
 'cheap',
 'check claims',
 'collect',
 'compare rates cost',
 'credit',
 'credit bureaus',
 'discount',
 'earn',
 'easy terms',
 'free',
 'fast cash',
 'for just $xxx hidden assets ',
 'hidden charges',
 'income incredible deal',
 'insurance ',
 'investment loans',
 'lowest price ',
 'million dollars money',
 'money back',
 'mortgage mortgage rates ',
 'no cost',
 'no fees',
 'one hundred percent free ',
 'only $ ',
 'pennies a day',
 'price',
 'profits ',
 'pure profit quote',
 'refinance',
 'save $ save big money',
 'save up to',
 'serious cash subject to credit',
 'they keep your money -- no refund! ',
 'unsecured credit unsecured debt',
 'us dollars',
 'why pay more?',
 'financial - business accept credit cards',
 'cards accepted',
 'check or money order',
 'credit card offers ',
 'explode your business',
 'full refund',
 'investment decision ',
 'no credit check ',
 'no hidden costs no investment',
 'requires initial investment',
 'sent in compliance stock alert ',
 'stock disclaimer statement ',
 'stock pick',
 'financial - personal avoid bankruptcy',
 'calling creditors',
 'collect child support consolidate debt and credit',
 'consolidate your debt',
 'eliminate bad credit',
 'eliminate debt',
 'financially independent',
 'get out of debt get paid ',
 'lower interest rate',
 'lower monthly payment',
 'lower your mortgage rate',
 'lowest insurance rates',
 'pre-approved refinance home ',
 'social security number ',
 'your income general acceptance',
 'accordingly',
 'avoid chance',
 'dormant',
 'freedom here',
 'hidden',
 'home leave',
 'lifetime',
 'lose maintained',
 'medium',
 'miracle never',
 'passwords',
 'problem remove',
 'reverses',
 'sample satisfaction',
 'solution',
 'stop success',
 'teen',
 'wife greetings dear [email/friend/somebody] ',
 'friend',
 'hello marketing ad',
 'auto email removal ',
 'bulk email click',
 'click below',
 'click here click to remove ',
 'direct email ',
 'direct marketing',
 'email harvest ',
 'email marketing ',
 'form increase sales ',
 'increase traffic ',
 'increase your sales internet market',
 'internet marketing',
 'marketing marketing solutions ',
 'mass email ',
 'member month trial offer',
 'more internet traffic',
 'multi level marketing notspam',
 'one time mailing ',
 'online marketing open',
 'opt in',
 'performance removal instructions',
 'sale',
 'sales search engine listings',
 'search engines',
 'subscribe the following form',
 "this isn't junk ",
 "this isn't spam",
 'undisclosed recipient',
 'unsubscribe',
 'visit our website we hate spam ',
 'web traffic',
 'will not believe your eyes',
 'medical cures baldness ',
 'diagnostics',
 'fast viagra delivery human growth hormone',
 'life insurance',
 'lose weight lose weight spam ',
 'medicine',
 'no medical exams online pharmacy ',
 'removes wrinkles',
 'reverses aging stop snoring ',
 'valium',
 'viagra vicodin',
 'weight loss',
 'xanax numbers #1',
 '100% free',
 '100% satisfied 4u',
 '50% off',
 'billion billion dollars ',
 'join millions',
 'join millions of americans',
 'million',
 'one hundred percent guaranteed ',
 'thousands offers being a member',
 'billing address ',
 'call cannot be combined with any other offer ',
 'confidentially on all orders ',
 'deal financial freedom ',
 'gift certificate',
 'giving away guarantee ',
 'have you been turned down? ',
 'if only it were that easy important information regarding',
 'in accordance with laws',
 'long distance phone offer mail in order form ',
 'message contains',
 'name brand',
 'nigerian ',
 'no age restrictions ',
 'no catch',
 'no claim forms ',
 'no disappointment ',
 'no experience',
 'no gimmick ',
 'no inventory ',
 'no middleman no obligation',
 'no purchase necessary',
 'no questions asked no selling',
 'no strings attached',
 'no-obligation not intended ',
 'obligation',
 'off shore offer',
 'per day',
 'per week priority mail',
 'prize',
 'prizes produced and sent out ',
 'reserves the right',
 'shopping spree',
 'stuff on sale',
 'terms and conditions',
 'the best rates they’re just giving it away',
 'trial',
 'unlimited unsolicited',
 'vacation',
 'vacation offers warranty',
 'we honor all ',
 'weekend getaway',
 'what are you waiting for? ',
 'who really wins? ',
 'win winner ',
 'winning ',
 'won you are a winner!',
 'you have been selected ',
 'you’re a winner! calls-to-action cancel at any time ',
 'compare',
 'copy accurately',
 'get',
 'give it away',
 'print form signature print out and fax ',
 'see for yourself',
 'sign up free today',
 'free free',
 'free access ',
 'free cell phone',
 'free consultation ',
 'free dvd ',
 'free gift free grant money',
 'free hosting',
 'free installation',
 'free instant',
 'free investment ',
 'free leads',
 'free membership ',
 'free money ',
 'free offer',
 'free preview ',
 'free priority mail ',
 'free quote',
 'free sample ',
 'free trial ',
 'free website',
 ' descriptions/adjectives all natural',
 'all new',
 'amazing',
 'certified',
 'congratulations ',
 'drastically reduced',
 'fantastic deal ',
 'for free ',
 'guaranteed it’s effective',
 'outstanding values ',
 'promise you real thing',
 'risk free',
 'satisfaction guaranteed',
 'sense of urgency access',
 'act now!',
 'apply now apply online ',
 'call free ',
 'call now',
 "can't live without",
 'do it today',
 "don't delete",
 "don't hesitate",
 'for instant access ',
 'for only for you',
 'get it now',
 'get started now',
 'great offer ',
 'info you requested',
 'information you requested instant',
 'limited time',
 'new customers only',
 'now',
 'now only',
 'offer expires',
 'once in lifetime ',
 'one time',
 'only order now',
 'order today',
 'please read',
 'special promotion ',
 'supplies are limited',
 'take action now time limited',
 'urgent',
 'while supplies last',
 'nouns addresses on cd',
 'beverage',
 'bonus brand new pager ',
 'cable converter ',
 'casino',
 'celebrity',
 'copy dvds ',
 'laser printer',
 'legal',
 'luxury car ',
 'new domain extensions',
 'phone',
 'rolex',
 'stainless steel',
 'money',
 'win',
 'beneficial offer',
 ]